### ISSUE TITLE
Fix font loading

### ISSUE THREAD

**Issue by mrexodia** [codecat/catsight#1]
When starting catsight some exceptions are thrown when trying to load `fonts/DroidSansMono.ttf` and `fonts/DroidSans-Bold.ttf`. Works fine with the attached folder next to `catsight.exe`. I downloaded them from https://www.fontsquirrel.com.

[fonts.zip](https://github.com/codecat/catsight/files/6219349/fonts.zip)

You could either embed the fonts with some cmake magic, or copy them at configure/install time to the appropriate locations.

**Comment by codecat** [comment]
Thanks for the report! The fonts you found were a bit different from the files I was using, which is also what's causing #2, although I will do a proper fix for that.
